language: python
python:
  - "2.7"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python manage.py test
