# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0002_bindserver_dns_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindserver',
            name='dns_port',
            field=models.IntegerField(default=53, help_text=b'The port where the BIND server is listening for DNS requests. binder especially uses that port for the dynamic zone updates. In most cases you should always leave it at the default port 53.', verbose_name=b'DNS port'),
        ),
    ]
